server:
  port: 8762

zuul:
  routes:
    auth-service:
      path: /auth-service/**
      serviceId: auth-service


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:5000/eureka}


# allow endpoints for actuator (on microservice)
management:
  endpoints:
    web:
      exposure:
        include: "*"